### ISSUE TITLE
Integration / acceptance tests for CDN broker

### ISSUE THREAD

**Issue by jmcarp** [18F/cf-cdn-service-broker#18]
Since this application is mostly glue between Let's Encrypt and various AWS tools, we'll likely want integration tests to be confident that everything is working as expected. Unfortunately, these tests are going to take a while to run, since provisioning a new CloudFront distribution can take 30 minutes.

**Comment by afeld** [comment]
Closed by https://github.com/18F/cf-cdn-service-broker/pull/51.
