### ISSUE TITLE
Set up IAM user

### ISSUE THREAD

**Issue by jmcarp** [18F/cf-cdn-service-broker#19]
The broker needs an account that can:
* Get/Create/Delete CloudFront distributions
* Upload/Delete SSL certs via IAM
* Put/Delete objects in an S3 bucket, which also needs to exist

I'm thinking it would make sense to set a configurable prefix on these resources so that we don't have to let the broker read/write all cloudfront distributions etc.

@dlapiduz can you help with this?

**Comment by dlapiduz** [comment]
This is the policy I used:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1,
            "Effect": "Allow",
            "Action": [
                "iam:DeleteServerCertificate",
                "iam:ListServerCertificates",
                "iam:UploadServerCertificate"
            ],
            "Resource": [
                "arn:aws:iam::acct#:server-certificate/cloudfront/cg/*"
            ]
        },
        {
            "Sid": "Stmt2",
            "Effect": "Allow",
            "Action": [
                "cloudfront:*"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "Stmt3",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::bucket/*"
            ]
        },
        {
            "Sid": "Stmt1466802441001",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::bucket"
            ]
        }
    ]
}
```

**Comment by jmcarp** [comment]
Can you add `s3:DeleteObject` too? The broker deletes let's encrypt tokens from S3 after we get the cert.

**Comment by dlapiduz** [comment]
Done

On Mon, Jun 27, 2016 at 10:10 PM, Joshua Carp <notifications@github.com>
wrote:

> Can you add s3:DeleteObject too? The broker deletes let's encrypt tokens
> from S3 after we get the cert.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/cf-cdn-service-broker/issues/19#issuecomment-228936806>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAR_Po3aRWggst9vlsmCB2vK18wSQ3gks5qQJDAgaJpZM4I-HqA>
> .
>



-- 
Diego Lapiduz
Director of cloud.gov
diego.lapiduz@gsa.gov
512 766 3434

**Comment by jmcarp** [comment]
Ugh, sorry, looks like we also need `iam:UpdateServerCertificate`. Sorry this is taking a while, but every change to a cloudfront distribution takes ~30m to propagate, so I'm basically working on this five minutes out of an hour.

**Comment by dlapiduz** [comment]
@jmcarp can we close this?

**Comment by jmcarp** [comment]
Yep. Should probably add it to terraform at some point too, but that's a separate issue.
