### ISSUE TITLE
Deploy CDN service broker

### ISSUE THREAD

**Issue by jmcarp** [18F/cf-cdn-service-broker#3]
Need to figure out where the service broker app lives. My impression is that the simplest thing for testing is to run the service as a vanilla cf app as described by https://blog.starkandwayne.com/2015/11/18/register-your-own-service-broker-with-any-cloud-foundry/, but I'm not sure what we'd do for production.

cc @afeld @dlapiduz

**Comment by dlapiduz** [comment]
@jmcarp you can deploy it to the `cf` org and `services` space if you want or you can deploy it to your sandbox until we figure out if it is ready. If you need AWS creds just DM me.

**Comment by jmcarp** [comment]
One more thing--the broker uses postgres to track service instances and an s3 bucket to serve let's encrypt tokens. Should those be provisioned using existing services, or is it a problem for the cdn broker to depend on the rds and s3 brokers?

**Comment by afeld** [comment]
No objection from me!

**Comment by dlapiduz** [comment]
@jmcarp I don't think it is a problem...

**Comment by dlapiduz** [comment]
It is manually deployed now, I think we should create a story for concourse deployment and close this one...

**Comment by mogul** [comment]
@jmcarp says that the deployment is automated now, albeit with tech debt. Considering this done for now.
