### ISSUE TITLE
As a user, I want to be able to update my CDN service settings

### ISSUE THREAD

**Issue by afeld** [18F/cf-cdn-service-broker#43]
Deleting or re-creating the service instance to change the `domain` or the `origin` (particularly the latter) will cause downtime and require DNS changes...we want to be able to change one or both on an existing instance to be able to migrate applications from, say, East/West to GovCloud.

/cc @jmcarp 

## Acceptance criteria

* [ ] User can change the `domain`
* [ ] User can change the `origin`

**Comment by amaline** [comment]
Would like to be able to update the cookie forwarding policy (all, none, or the list of cookies specified) as well.

**Comment by afeld** [comment]
@amaline Noted. Created https://github.com/18F/cf-cdn-service-broker/issues/50 to discuss it.

**Comment by afeld** [comment]
(and thanks for the input!)
