### ISSUE TITLE
Allow CDN broker to forward all headers

### ISSUE THREAD

**Issue by afeld** [18F/cf-cdn-service-broker#46]
@sharms commented on [Fri Dec 16 2016](https://github.com/18F/cg-product/issues/571)

In order to enable applications to work as expected, customers should be able to configure which original headers should be forwarded. 

Notes:  Otherwise login pages etc may be cached instead of working properly.

**Acceptance Criteria:**
- [ ] Method of setting headers to be forwarded when using CDN broker
- [ ] Instructions are on docs.cloud.gov

**Comment by afeld** [comment]
Potentially part of #50.

**Comment by 46bit** [comment]
This seems resolved by #90.

**Comment by afeld** [comment]
Awesome, thanks!
