### ISSUE TITLE
Add option to log user requests to S3 bucket

### ISSUE THREAD

**Issue by berndverst** [18F/cf-cdn-service-broker#53]
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#access-logs-choosing-s3-bucket

This would probably be a parameter as part of the CDN broker creation and would require that the S3 bucket was created via one of the S3 service plans.

**Comment by mogul** [comment]
We're expecting this to be taken care of by https://github.com/18F/cf-cdn-service-broker/issues/50. /cc @amaline
