### ISSUE TITLE
LambdaFunctionAssociations is required when updating a distribution

### ISSUE THREAD

**Issue by jfredrickson5** [18F/cf-cdn-service-broker#61]
Using `cf update-service` on an existing CDN route service results in:

```
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: InvalidArgument: The parameter Lambda function associations is required.
```

Turns out CloudFront requires the LambdaFunctionAssociations parameter in CacheBehavior. The AWS docs are [inaccurate in saying that it is not required](https://docs.aws.amazon.com/AmazonCloudFront/latest/APIReference/API_CacheBehavior.html).

[Terraform had trouble with this too; see this issue for inspiration](https://github.com/hashicorp/terraform/issues/10938).

**Comment by afeld** [comment]
I'd suggest posting something in the AWS Forum as well, suggesting it be fixed in the docs.
