### ISSUE TITLE
investigate if certbot can be used

### ISSUE THREAD

**Issue by afeld** [18F/cf-cdn-service-broker#7]
Seems like that's now the recommended tool...wondering if we can leverage it somehow?

https://letsencrypt.org/getting-started/

**Comment by jmcarp** [comment]
The certbot/letsencrypt cli is written in python, so we'd need to shell out to use it here. Plus, it wants root access by default. Lego seems like the most mature acme client written in go, and is used in caddy, which is where I found it in the first place (thanks @dlapiduz for pointing that out).

**Comment by afeld** [comment]
Cool cool. Let's stick with this then!
